development:
  adapter: postgresql
  database: twist_dev
  username: <%= ENV['db_username'] %>
  password: <%= ENV['db_password'] %>

test:
  adapter: postgresql
  database: twist_test
  username: <%= ENV['db_username'] %>
  password: <%= ENV['db_password'] %>
